// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
	export interface GlobalComponents {
		404: typeof import('./../src/components/error/404.vue')['default'];
		ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider'];
		ElOption: typeof import('element-plus/es')['ElOption'];
		ElSelect: typeof import('element-plus/es')['ElSelect'];
		IconifyIcon: typeof import('./../src/components/Icon/src/IconifyIcon.vue')['default'];
		IconPicker: typeof import('./../src/components/Icon/src/IconPicker.vue')['default'];
		RouterLink: typeof import('vue-router')['RouterLink'];
		RouterView: typeof import('vue-router')['RouterView'];
		SvgIcon: typeof import('./../src/components/Icon/src/SvgIcon.vue')['default'];
	}
}
